// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QanoonCoalition.Web.Data;

#nullable disable

namespace QanoonCoalition.Web.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260827164442_AddCitizenRequestsModule")]
    partial class AddCitizenRequestsModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QanoonCoalition.Web.Models.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EntityId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int?>("MovementId")
                        .HasColumnType("int");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Action")
                        .HasDatabaseName("IX_AuditLogs_Action");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_AuditLogs_CreatedAt");

                    b.HasIndex("MovementId")
                        .HasDatabaseName("IX_AuditLogs_MovementId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_AuditLogs_UserId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("QanoonCoalition.Web.Models.CitizenRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AnswerDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApplicantEmail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ApplicantName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ApplicantPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ContactInformation")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("DestinationId")
                        .HasColumnType("int");

                    b.Property<string>("DestinationSubText")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MovementId")
                        .HasColumnType("int");

                    b.Property<int?>("ReceivedByMemberId")
                        .HasColumnType("int");

                    b.Property<string>("RequestCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestSubject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("SentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DestinationId");

                    b.HasIndex("MovementId");

                    b.HasIndex("ReceivedByMemberId");

                    b.HasIndex("RequestCode")
                        .IsUnique();

                    b.HasIndex("RequestDate");

                    b.HasIndex("StatusId");

                    b.ToTable("CitizenRequests", (string)null);
                });

            modelBuilder.Entity("QanoonCoalition.Web.Models.CitizenRequestAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CitizenRequestId")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CitizenRequestId");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("CitizenRequestAttachments", (string)null);
                });

            modelBuilder.Entity("QanoonCoalition.Web.Models.CitizenRequestStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorClass")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder");

                    b.ToTable("CitizenRequestStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorClass = "warning",
                            DisplayOrder = 1,
                            IsActive = true,
                            IsDefault = true,
                            Name = "مستلم"
                        },
                        new
                        {
                            Id = 2,
                            ColorClass = "primary",
                            DisplayOrder = 2,
                            IsActive = true,
                            IsDefault = false,
                            Name = "مرسل"
                        },
                        new
                        {
                            Id = 3,
                            ColorClass = "info",
                            DisplayOrder = 3,
                            IsActive = true,
                            IsDefault = false,
                            Name = "إجابة عنه"
                        },
                        new
                        {
                            Id = 4,
                            ColorClass = "success",
                            DisplayOrder = 4,
                            IsActive = true,
                            IsDefault = false,
                            Name = "منجز"
                        });
                });

            modelBuilder.Entity("QanoonCoalition.Web.Models.CitizenRequestStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ChangedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("CitizenRequestId")
                        .HasColumnType("int");

                    b.Property<int?>("FromStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ToStatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("CitizenRequestId");

                    b.HasIndex("FromStatusId");

                    b.HasIndex("ToStatusId");

                    b.ToTable("CitizenRequestStatusHistory", (string)null);
                });

            modelBuilder.Entity("QanoonCoalition.Web.Models.DocumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("DocumentTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "كتاب"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "طلب"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "كتاب إرسال"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "إجابة"
                        });
                });

            modelBuilder.Entity("QanoonCoalition.Web.Models.JoinRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BenefitField")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EducationLevel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Experiences")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .UseCollation("Arabic_CI_AI");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Languages")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MovementId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Occupation")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ServiceStartDate")
                        .HasColumnType("date");

                    b.Property<int?>("ServiceYears")
                        .HasColumnType("int");

                    b.Property<string>("Skills")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Specialization")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("SubDistrict")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("TrainingCourses")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("WorkPlace")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("MovementId");

                    b.HasIndex("ReferenceNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_JoinRequests_ReferenceNumber");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_JoinRequests_Status");

                    b.HasIndex("Phone", "MovementId")
                        .HasDatabaseName("IX_JoinRequests_Phone_Movement");

                    b.ToTable("JoinRequests", (string)null);
                });

            modelBuilder.Entity("QanoonCoalition.Web.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("BenefitField")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EducationLevel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Experiences")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .UseCollation("Arabic_CI_AI");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("JoinRequestId")
                        .HasColumnType("int");

                    b.Property<string>("Languages")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MovementId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Occupation")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)")
                        .IsFixedLength();

                    b.Property<DateOnly?>("ServiceStartDate")
                        .HasColumnType("date");

                    b.Property<int?>("ServiceYears")
                        .HasColumnType("int");

                    b.Property<string>("Skills")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Specialization")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SubDistrict")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrainingCourses")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("WorkPlace")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Members_Email")
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("FullName")
                        .IsUnique()
                        .HasDatabaseName("IX_Members_FullName");

                    b.HasIndex("JoinRequestId")
                        .IsUnique()
                        .HasFilter("[JoinRequestId] IS NOT NULL");

                    b.HasIndex("MovementId");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasDatabaseName("IX_Members_Phone");

                    b.HasIndex("SerialNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Members_SerialNumber");

                    b.ToTable("Members", (string)null);
                });

            modelBuilder.Entity("QanoonCoalition.Web.Models.Movement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Governorate")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Logo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .UseCollation("Arabic_CI_AI");

                    b.Property<string>("NameSlug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PublicToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Movements_Name");

                    b.HasIndex("NameSlug")
                        .IsUnique()
                        .HasDatabaseName("IX_Movements_NameSlug");

                    b.HasIndex("PublicToken")
                        .IsUnique()
                        .HasDatabaseName("IX_Movements_PublicToken");

                    b.ToTable("Movements", (string)null);
                });

            modelBuilder.Entity("QanoonCoalition.Web.Models.MovementConstant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("text");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MovementId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("MovementId", "Key")
                        .IsUnique()
                        .HasDatabaseName("IX_MovementConstants_MovementId_Key");

                    b.ToTable("MovementConstants", (string)null);
                });

            modelBuilder.Entity("QanoonCoalition.Web.Models.RequestDestination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder");

                    b.ToTable("RequestDestinations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "وزارة الداخلية",
                            Type = "وزارة"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "وزارة الخارجية",
                            Type = "وزارة"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "وزارة المالية",
                            Type = "وزارة"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "وزارة التعليم",
                            Type = "وزارة"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            IsActive = true,
                            Name = "وزارة الصحة",
                            Type = "وزارة"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            IsActive = true,
                            Name = "وزارة العدل",
                            Type = "وزارة"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            IsActive = true,
                            Name = "وزارة الكهرباء",
                            Type = "وزارة"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            IsActive = true,
                            Name = "وزارة الإعمار",
                            Type = "وزارة"
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 9,
                            IsActive = true,
                            Name = "وزارة الاتصالات",
                            Type = "وزارة"
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 10,
                            IsActive = true,
                            Name = "وزارة الموارد المائية",
                            Type = "وزارة"
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 11,
                            IsActive = true,
                            Name = "هيئة النزاهة",
                            Type = "هيئة"
                        },
                        new
                        {
                            Id = 12,
                            DisplayOrder = 12,
                            IsActive = true,
                            Name = "هيئة الاستثمار",
                            Type = "هيئة"
                        },
                        new
                        {
                            Id = 13,
                            DisplayOrder = 13,
                            IsActive = true,
                            Name = "مجلس القضاء الأعلى",
                            Type = "هيئة"
                        },
                        new
                        {
                            Id = 14,
                            DisplayOrder = 14,
                            IsActive = true,
                            Name = "الأمانة العامة لمجلس الوزراء",
                            Type = "دائرة"
                        },
                        new
                        {
                            Id = 15,
                            DisplayOrder = 15,
                            IsActive = true,
                            Name = "محافظة بغداد",
                            Type = "محافظة"
                        },
                        new
                        {
                            Id = 16,
                            DisplayOrder = 16,
                            IsActive = true,
                            Name = "محافظة البصرة",
                            Type = "محافظة"
                        },
                        new
                        {
                            Id = 17,
                            DisplayOrder = 17,
                            IsActive = true,
                            Name = "محافظة النجف",
                            Type = "محافظة"
                        },
                        new
                        {
                            Id = 18,
                            DisplayOrder = 18,
                            IsActive = true,
                            Name = "محافظة كربلاء",
                            Type = "محافظة"
                        },
                        new
                        {
                            Id = 19,
                            DisplayOrder = 19,
                            IsActive = true,
                            Name = "مؤسسة الشهداء",
                            Type = "مؤسسة"
                        },
                        new
                        {
                            Id = 20,
                            DisplayOrder = 20,
                            IsActive = true,
                            Name = "جهة أخرى",
                            Type = "أخرى"
                        });
                });

            modelBuilder.Entity("QanoonCoalition.Web.Models.SystemConstant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Category", "Value")
                        .IsUnique();

                    b.ToTable("SystemConstants", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "EducationLevel",
                            DisplayOrder = 2,
                            IsActive = true,
                            Value = "أمي"
                        },
                        new
                        {
                            Id = 2,
                            Category = "EducationLevel",
                            DisplayOrder = 3,
                            IsActive = true,
                            Value = "يقرأ ويكتب"
                        },
                        new
                        {
                            Id = 3,
                            Category = "EducationLevel",
                            DisplayOrder = 4,
                            IsActive = true,
                            Value = "ابتدائية"
                        },
                        new
                        {
                            Id = 4,
                            Category = "EducationLevel",
                            DisplayOrder = 5,
                            IsActive = true,
                            Value = "متوسطة"
                        },
                        new
                        {
                            Id = 5,
                            Category = "EducationLevel",
                            DisplayOrder = 6,
                            IsActive = true,
                            Value = "إعدادية"
                        },
                        new
                        {
                            Id = 6,
                            Category = "EducationLevel",
                            DisplayOrder = 7,
                            IsActive = true,
                            Value = "دبلوم"
                        },
                        new
                        {
                            Id = 7,
                            Category = "EducationLevel",
                            DisplayOrder = 8,
                            IsActive = true,
                            Value = "بكالوريوس"
                        },
                        new
                        {
                            Id = 8,
                            Category = "EducationLevel",
                            DisplayOrder = 9,
                            IsActive = true,
                            Value = "دبلوم عالي"
                        },
                        new
                        {
                            Id = 9,
                            Category = "EducationLevel",
                            DisplayOrder = 10,
                            IsActive = true,
                            Value = "ماجستير"
                        },
                        new
                        {
                            Id = 10,
                            Category = "EducationLevel",
                            DisplayOrder = 11,
                            IsActive = true,
                            Value = "دكتوراه"
                        },
                        new
                        {
                            Id = 11,
                            Category = "BenefitField",
                            DisplayOrder = 12,
                            IsActive = true,
                            Value = "تنظيمي وإداري"
                        },
                        new
                        {
                            Id = 12,
                            Category = "BenefitField",
                            DisplayOrder = 13,
                            IsActive = true,
                            Value = "إعلامي"
                        },
                        new
                        {
                            Id = 13,
                            Category = "BenefitField",
                            DisplayOrder = 14,
                            IsActive = true,
                            Value = "قانوني"
                        },
                        new
                        {
                            Id = 14,
                            Category = "BenefitField",
                            DisplayOrder = 15,
                            IsActive = true,
                            Value = "مالي ومحاسبي"
                        },
                        new
                        {
                            Id = 15,
                            Category = "BenefitField",
                            DisplayOrder = 16,
                            IsActive = true,
                            Value = "طبي وصحي"
                        },
                        new
                        {
                            Id = 16,
                            Category = "BenefitField",
                            DisplayOrder = 17,
                            IsActive = true,
                            Value = "هندسي وفني"
                        },
                        new
                        {
                            Id = 17,
                            Category = "BenefitField",
                            DisplayOrder = 18,
                            IsActive = true,
                            Value = "تربوي وتعليمي"
                        },
                        new
                        {
                            Id = 18,
                            Category = "BenefitField",
                            DisplayOrder = 19,
                            IsActive = true,
                            Value = "تقنية المعلومات"
                        },
                        new
                        {
                            Id = 19,
                            Category = "BenefitField",
                            DisplayOrder = 20,
                            IsActive = true,
                            Value = "علاقات عامة"
                        },
                        new
                        {
                            Id = 20,
                            Category = "BenefitField",
                            DisplayOrder = 21,
                            IsActive = true,
                            Value = "لوجستي وخدمي"
                        },
                        new
                        {
                            Id = 21,
                            Category = "BenefitField",
                            DisplayOrder = 22,
                            IsActive = true,
                            Value = "تحريري وجماهيري"
                        },
                        new
                        {
                            Id = 22,
                            Category = "BenefitField",
                            DisplayOrder = 23,
                            IsActive = true,
                            Value = "بحوث ودراسات"
                        },
                        new
                        {
                            Id = 23,
                            Category = "BenefitField",
                            DisplayOrder = 24,
                            IsActive = true,
                            Value = "أخرى"
                        },
                        new
                        {
                            Id = 24,
                            Category = "ManagerTitle",
                            DisplayOrder = 25,
                            IsActive = true,
                            Value = "رئيس"
                        },
                        new
                        {
                            Id = 25,
                            Category = "ManagerTitle",
                            DisplayOrder = 26,
                            IsActive = true,
                            Value = "نائب رئيس"
                        },
                        new
                        {
                            Id = 26,
                            Category = "ManagerTitle",
                            DisplayOrder = 27,
                            IsActive = true,
                            Value = "أمين سر"
                        },
                        new
                        {
                            Id = 27,
                            Category = "ManagerTitle",
                            DisplayOrder = 28,
                            IsActive = true,
                            Value = "عضو مجلس"
                        },
                        new
                        {
                            Id = 28,
                            Category = "ManagerTitle",
                            DisplayOrder = 29,
                            IsActive = true,
                            Value = "موظف"
                        },
                        new
                        {
                            Id = 29,
                            Category = "ManagerTitle",
                            DisplayOrder = 30,
                            IsActive = true,
                            Value = "منسق"
                        },
                        new
                        {
                            Id = 30,
                            Category = "ManagerTitle",
                            DisplayOrder = 31,
                            IsActive = true,
                            Value = "متطوع"
                        });
                });

            modelBuilder.Entity("QanoonCoalition.Web.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MovementId")
                        .HasColumnType("int");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("PasswordResetExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.HasIndex("MovementId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("QanoonCoalition.Web.Models.AuditLog", b =>
                {
                    b.HasOne("QanoonCoalition.Web.Models.Movement", "Movement")
                        .WithMany("AuditLogs")
                        .HasForeignKey("MovementId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QanoonCoalition.Web.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Movement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QanoonCoalition.Web.Models.CitizenRequest", b =>
                {
                    b.HasOne("QanoonCoalition.Web.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QanoonCoalition.Web.Models.RequestDestination", "Destination")
                        .WithMany("CitizenRequests")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QanoonCoalition.Web.Models.Movement", "Movement")
                        .WithMany()
                        .HasForeignKey("MovementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QanoonCoalition.Web.Models.Member", "ReceivedByMember")
                        .WithMany()
                        .HasForeignKey("ReceivedByMemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QanoonCoalition.Web.Models.CitizenRequestStatus", "Status")
                        .WithMany("CitizenRequests")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Destination");

                    b.Navigation("Movement");

                    b.Navigation("ReceivedByMember");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("QanoonCoalition.Web.Models.CitizenRequestAttachment", b =>
                {
                    b.HasOne("QanoonCoalition.Web.Models.CitizenRequest", "CitizenRequest")
                        .WithMany("Attachments")
                        .HasForeignKey("CitizenRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QanoonCoalition.Web.Models.DocumentType", "DocumentType")
                        .WithMany("Attachments")
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QanoonCoalition.Web.Models.User", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CitizenRequest");

                    b.Navigation("DocumentType");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("QanoonCoalition.Web.Models.CitizenRequestStatusHistory", b =>
                {
                    b.HasOne("QanoonCoalition.Web.Models.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QanoonCoalition.Web.Models.CitizenRequest", "CitizenRequest")
                        .WithMany("StatusHistory")
                        .HasForeignKey("CitizenRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QanoonCoalition.Web.Models.CitizenRequestStatus", "FromStatus")
                        .WithMany()
                        .HasForeignKey("FromStatusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QanoonCoalition.Web.Models.CitizenRequestStatus", "ToStatus")
                        .WithMany()
                        .HasForeignKey("ToStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("CitizenRequest");

                    b.Navigation("FromStatus");

                    b.Navigation("ToStatus");
                });

            modelBuilder.Entity("QanoonCoalition.Web.Models.JoinRequest", b =>
                {
                    b.HasOne("QanoonCoalition.Web.Models.Movement", "Movement")
                        .WithMany("JoinRequests")
                        .HasForeignKey("MovementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QanoonCoalition.Web.Models.User", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Movement");

                    b.Navigation("ReviewedByUser");
                });

            modelBuilder.Entity("QanoonCoalition.Web.Models.Member", b =>
                {
                    b.HasOne("QanoonCoalition.Web.Models.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QanoonCoalition.Web.Models.JoinRequest", "JoinRequest")
                        .WithOne("ConvertedMember")
                        .HasForeignKey("QanoonCoalition.Web.Models.Member", "JoinRequestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QanoonCoalition.Web.Models.Movement", "Movement")
                        .WithMany("Members")
                        .HasForeignKey("MovementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("JoinRequest");

                    b.Navigation("Movement");
                });

            modelBuilder.Entity("QanoonCoalition.Web.Models.Movement", b =>
                {
                    b.HasOne("QanoonCoalition.Web.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("QanoonCoalition.Web.Models.MovementConstant", b =>
                {
                    b.HasOne("QanoonCoalition.Web.Models.Movement", "Movement")
                        .WithMany("Constants")
                        .HasForeignKey("MovementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movement");
                });

            modelBuilder.Entity("QanoonCoalition.Web.Models.User", b =>
                {
                    b.HasOne("QanoonCoalition.Web.Models.Movement", "Movement")
                        .WithMany("Managers")
                        .HasForeignKey("MovementId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Movement");
                });

            modelBuilder.Entity("QanoonCoalition.Web.Models.CitizenRequest", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("QanoonCoalition.Web.Models.CitizenRequestStatus", b =>
                {
                    b.Navigation("CitizenRequests");
                });

            modelBuilder.Entity("QanoonCoalition.Web.Models.DocumentType", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("QanoonCoalition.Web.Models.JoinRequest", b =>
                {
                    b.Navigation("ConvertedMember");
                });

            modelBuilder.Entity("QanoonCoalition.Web.Models.Movement", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Constants");

                    b.Navigation("JoinRequests");

                    b.Navigation("Managers");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("QanoonCoalition.Web.Models.RequestDestination", b =>
                {
                    b.Navigation("CitizenRequests");
                });

            modelBuilder.Entity("QanoonCoalition.Web.Models.User", b =>
                {
                    b.Navigation("AuditLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
